### ISSUE TITLE
May support Xray-core?

### ISSUE THREAD

**Issue by orivee** [xmapst/v2ray-tracing#1]
I like this project to visualize v2ray, so I try to use it with Xray, but it doesn't work.

I get error as below:

```
time="2022-05-06T20:45:23+08:00" level=info msg="connected to 127.0.0.1:10805" func=Logf file="entry.go:314"
time="2022-05-06T20:45:23+08:00" level=error msg="logger service error: rpc error: code = Unimplemented desc = unknown method FollowLog for service v2ray.core.app.log.command.LoggerService" func=Logf file="entry.go:314"
time="2022-05-06T20:45:23+08:00" level=error msg="Failed to get system stats: rpc error: code = Canceled desc = grpc: the client connection is closing" func=Log file="logger.go:192"
time="2022-05-06T20:45:23+08:00" level=error msg="Failed to query stats: rpc error: code = Canceled desc = grpc: the client connection is closing" func=Log file="logger.go:192"
```
I hope maybe to support Xray. 

Thanks.

**Comment by xmapst** [comment]
> I like this project to visualize v2ray, so I try to use it with Xray, but it doesn't work.
> 
> I get error as below:
> 
> ```
> time="2022-05-06T20:45:23+08:00" level=info msg="connected to 127.0.0.1:10805" func=Logf file="entry.go:314"
> time="2022-05-06T20:45:23+08:00" level=error msg="logger service error: rpc error: code = Unimplemented desc = unknown method FollowLog for service v2ray.core.app.log.command.LoggerService" func=Logf file="entry.go:314"
> time="2022-05-06T20:45:23+08:00" level=error msg="Failed to get system stats: rpc error: code = Canceled desc = grpc: the client connection is closing" func=Log file="logger.go:192"
> time="2022-05-06T20:45:23+08:00" level=error msg="Failed to query stats: rpc error: code = Canceled desc = grpc: the client connection is closing" func=Log file="logger.go:192"
> ```
> 
> I hope maybe to support Xray.
> 
> Thanks.

你是否启用了LoggerService?

**Comment by orivee** [comment]
> 你是否启用了LoggerService?

已经启用了，我在 Xray-core 中没有找到 `FollowLog` 方法的实现，不知道是不是这个原因？

**Comment by xmapst** [comment]
> > 你是否启用了LoggerService?
> 
> 已经启用了，我在 Xray-core 中没有找到 `FollowLog` 方法的实现，不知道是不是这个原因？

好的, 我明天测试看看

**Comment by xmapst** [comment]
> > 你是否启用了LoggerService?
> 
> 已经启用了，我在 Xray-core 中没有找到 `FollowLog` 方法的实现，不知道是不是这个原因？

`xray-core` 是从`v2ray-core` `v4`分离出去的, 而`FollowLog`是在`v2ray-core` `v5`中才实现的, 所以不支持`v2ray-core` `v4`版本以及`xray-core`
